tiles_dir : '/tmp/data' #Training/Test dir
tiles_color_normalized_dir : '/media/zw/Elements1/tiles_cn'
model_path : '/home/qiuwj/msipredictor/results/model.pkl'

test_dir : '/home/xisx/data/HE/xiehe/tiles_cn' 

ratio_train : 1  # training set ratio 训练集比例
ratio_test : 0.3  # test set ratio 测试集比例

num_epochs : 25  # epochs for training

use_lmdb : False
load_data_type : 2  # 0:dir  1: lmdb  2: file
k : 5
